feat(optimized matcher): Fix flaky test.
1) error handling async component errors
  Message:
    Expected spy warn to have been called once. It was called 0 times.
  Stack:
    Error: Expected spy warn to have been called once. It was called 0 times.
        at /home/iurisilvio/code/oss/vue-router/test/unit/specs/error-handling.spec.js:157:30
        at <anonymous>
        at processTicksAndRejections (internal/process/task_queues.js:95:5)